version: "3"

services:
  residentcare-frontend:
    image: dag254/residentcare:latest
    container_name: residentcare-frontend
    ports:
      - "80:80"
    restart: always

  watchtower-frontend:
    image: containrrr/watchtower
    container_name: watchtower-frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=5
    restart: always
